version: "3.2"
services:
  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=BiNdIgaralwa
      - POSTGRES_DB=db
    ports:
      - "5432"

  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "9000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=BiNdIgaralwa
      - SECRET_KEY=django-insecure-s6d0k%3ph&mdyyfslkz-!2wbuf1g36igjpbf-y55_oajtdh@+g

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "300"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data: